/* eslint-disable node/prefer-global/process */
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxt/image',
    'nuxt-jsonld',
    '@nuxtjs/google-fonts',
    'nuxt-icon',
    'nuxt-simple-robots',
  ],
  googleFonts: {
    families: {
      'Open Sans': true,
    },
  },
  runtimeConfig: {
    googlePropertyId: process.env.GOOGLE_PROPERTY_ID,
    googleApplicationCredentials: process.env.GOOGLE_APPLICATION_CREDENTIALS,
    public: {
      graphqlEndpoint: process.env.GRAPHQL_ENDPOINT,
      siteUrl: process.env.SITE_URL,
      siteName: process.env.SITE_NAME,
      siteSlogan: process.env.SITE_SLOGAN,
      siteDescriptionMeta: process.env.SITE_DESCRIPTION_META,
      siteKeywords: process.env.SITE_KEYWORDS,
      siteLogoUrl: process.env.SITE_LOGO_URL,
      siteThumbnailUrl: process.env.SITE_THUMBNAIL_URL,
      siteThumbnailWidth: process.env.SITE_THUMBNAIL_WIDTH,
      siteThumbnailHeight: process.env.SITE_THUMBNAIL_HEIGHT,
      siteThumbnailImageType: process.env.SITE_THUMBNAIL_IMAGE_TYPE,
      terpopulerDescriptionMeta: process.env.TERPOPULER_DESCRIPTION_META,
      terkiniDescriptionMeta: process.env.TERKINI_DESCRIPTION_META,
      twitterMetaName: process.env.TWITTER_META_NAME,
      twitterMetaUsername: process.env.TWITTER_META_USERNAME,
      pulicationName: process.env.PUBLICATION_NAME,
      urlFacebook: process.env.URL_FACEBOOK,
      urlTwitter: process.env.URL_TWITTER,
      urlInstagram: process.env.URL_INSTAGRAM,
      urlYoutube: process.env.URL_YOUTUBE,
      urlTiktok: process.env.URL_TIKTOK,
      postsLimit: process.env.POSTS_LIMIT,
      googleSiteVerification: process.env.GOOGLE_SITE_VERIFICATION,
    },
  },
  robots: {
    credits: false,
    allow: '*',
    sitemap: [
      `${process.env.SITE_URL}/sitemap.xml`,
      `${process.env.SITE_URL}/sitemap-basic.xml`,
      `${process.env.SITE_URL}/sitemap-feeds.xml`,
      `${process.env.SITE_URL}/sitemap-advertorial.xml`,
      `${process.env.SITE_URL}/sitemap-banjarnegara.xml`,
      `${process.env.SITE_URL}/sitemap-banyumas.xml`,
      `${process.env.SITE_URL}/sitemap-bisnis.xml`,
      `${process.env.SITE_URL}/sitemap-cek-fakta.xml`,
      `${process.env.SITE_URL}/sitemap-cilacap.xml`,
      `${process.env.SITE_URL}/sitemap-edukasi.xml`,
      `${process.env.SITE_URL}/sitemap-ekonomi.xml`,
      `${process.env.SITE_URL}/sitemap-entertainment.xml`,
      `${process.env.SITE_URL}/sitemap-health.xml`,
      `${process.env.SITE_URL}/sitemap-hukumkriminal.xml`,
      `${process.env.SITE_URL}/sitemap-inspirasi.xml`,
      `${process.env.SITE_URL}/sitemap-internasional.xml`,
      `${process.env.SITE_URL}/sitemap-kebumen.xml`,
      `${process.env.SITE_URL}/sitemap-kilas-jateng.xml`,
      `${process.env.SITE_URL}/sitemap-kuliner.xml`,
      `${process.env.SITE_URL}/sitemap-lifestyle.xml`,
      `${process.env.SITE_URL}/sitemap-muara-kata.xml`,
      `${process.env.SITE_URL}/sitemap-nasional.xml`,
      `${process.env.SITE_URL}/sitemap-news.xml`,
      `${process.env.SITE_URL}/sitemap-ngapak-diaspora.xml`,
      `${process.env.SITE_URL}/sitemap-opini.xml`,
      `${process.env.SITE_URL}/sitemap-otomotif.xml`,
      `${process.env.SITE_URL}/sitemap-pariwisata.xml`,
      `${process.env.SITE_URL}/sitemap-peristiwa.xml`,
      `${process.env.SITE_URL}/sitemap-politik.xml`,
      `${process.env.SITE_URL}/sitemap-purbalingga.xml`,
      `${process.env.SITE_URL}/sitemap-sport.xml`,
      `${process.env.SITE_URL}/sitemap-tekno.xml`,
      `${process.env.SITE_URL}/sitemap-tips-trick.xml`,
      `${process.env.SITE_URL}/sitemap-travel.xml`,
      `${process.env.SITE_URL}/sitemap-wonosobo.xml`,
      `${process.env.SITE_URL}/sitemap-authors.xml`,
      `${process.env.SITE_URL}/sitemap-images.xml`,
    ],
  },
})
